apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shopping
  name: shopping
  namespace: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping
  template:
    metadata:
      labels:
        app: shopping
    spec:
      imagePullSecrets:
        - name: ghcr
      containers:
      - image: ghcr.io/mkanus/argocd-app:latests
        name: shopping
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: shopping
  name: shopping-svc
  namespace: product
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: shopping
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: product
  name: shopping
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - argocd.mehmetkanus.com
    secretName: tls-argocd
  rules:
    - host: argocd.mehmetkanus.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shopping-svc
                port:
                  number: 80